# Generated by Django 2.1.4 on 2018-12-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_deliveryperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.FloatField(),
        ),
    ]
