# Generated by Django 2.1.4 on 2018-12-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20181229_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='phone_number',
            field=models.FloatField(),
        ),
    ]
