# Generated by Django 2.1.4 on 2018-12-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='S', max_length=50, verbose_name=(('O', 'Ordered'), ('S', 'Saved'), ('D', 'Delivered'))),
        ),
        migrations.AddField(
            model_name='cart',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
