# Generated by Django 2.1.4 on 2018-12-29 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181230_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='purchase',
        ),
        migrations.AddField(
            model_name='purchase',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Cart'),
            preserve_default=False,
        ),
    ]
