# Generated by Django 2.1.4 on 2018-12-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20181229_0556'),
        ('orders', '0003_auto_20181230_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name=(('R', 'Recived'), ('O', 'On The Way'), ('D', 'Delivered')))),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.CustomerAddress')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.Customer')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.DeliveryPerson')),
            ],
        ),
    ]
