# Generated by Django 2.1.4 on 2018-12-29 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='customer',
        ),
    ]
