# Generated by Django 2.1.4 on 2018-12-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181223_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='group',
        ),
    ]
