# Generated by Django 2.1.4 on 2018-12-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_brand_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
