# Generated by Django 2.1.4 on 2018-12-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181223_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductGroup'),
        ),
    ]
