# Generated by Django 2.1.4 on 2018-12-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20181223_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_unit',
            field=models.CharField(default='unit', max_length=50),
            preserve_default=False,
        ),
    ]
